#!/bin/bash

APP_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
APP_DIR="$APP_ROOT/Resources/obie"
SERVER="$APP_DIR/server.py"

python3 "$SERVER" &
SERVER_PID=$!

cleanup() {
    kill "$SERVER_PID" 2>/dev/null
    wait "$SERVER_PID" 2>/dev/null
}
trap cleanup EXIT INT TERM

sleep 1
open -na "Google Chrome" --args --app="http://127.0.0.1:8000"

wait "$SERVER_PID"
